[package]
name = "rsa_pow"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha256 = "1.5.0"
regex = "1.11.0"

sha2 = { version = "0.10.6", default-features = false, features = ["oid"] }
hex = "0.4.3"
rsa = "0.7.2"
